---
- name: Create folder to store artifacts if not exist
  win_file:
    path: 'C:\\Users\\Administrator\\Downloads\\artifactoty\\'
    state: directory
- name: Create folder to extract artifacts if not exist
  win_file:
    path: 'C:\\Users\\Administrator\\Downloads\\artifacts\\'
    state: directory

- name: Downloading maven artifacts
  win_get_url:
    url: http://localhost:8082/artifactory/service-common/com/dl/cc/service-common/1.0-SNAPSHOT/service-common-1.0-SNAPSHOT-{{ build_id }}.zip
    headers:  {"X-JFrog-Art-Api": ""}
#    url_username:
#    url_password:
    dest: 'C:\\Users\\Administrator\\Downloads\\artifactoty\\'

#- name: Downloading maven artifacts
#  maven_artifact:
#    group_id: ""
#    artifact_id: ""
#    repository_url: ''
#    username:
#    password:
#    dest: 'C:\\Users\\Administrator\\Downloads\\artifacts\\service-common-1.0-20200803.124758-1-{{ build_id }}.zip'

- name: Extract the artifacts
  win_unzip:
    src: 'C:\\Users\\Administrator\\Downloads\\artifactoty\\service-common-1.0-{{ build_id }}.zip'
    dest: 'C:\\Users\\Administrator\\Downloads\\artifacts\\'
    delete_archive: yes

#- name: Run the script to generate other script
#  win_shell: "C:\\Users\\Administrator\\Downloads\\artifacts\\Transport_Modeling\\bin\\start.bat"
#    args:
#      executable: cmd
#    register: output
#- debug: msg="{{maven_version.stderr_lines}}"